spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/hole5019/imooc_test.git
          username: hole5019
          password: helei19911005
          basedir: E:/GitRepo/basedir
eureka:
  client:
    service-url:
      defalutZone: http://localhost:8761/eureka/
server:
  port: 8764
management:
  endpoints:
    web:
#      expose: "*"
      exposure:
        include: bus-refresh
#        exclude: